# Generated by Django 2.1 on 2019-07-09 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeStampMode',
            new_name='TimeStampModel',
        ),
    ]
